USE [OptimusPrime]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS dbo.lt_FTP_WBS

CREATE TABLE [dbo].[lt_FTP_WBS](
WBS_Element NUMERIC (8) NOT NULL,
WorkBreakdownStructure NVARCHAR	(24) NULL,
PS_Desc NVARCHAR (40) NULL,
PROJ_Type NVARCHAR (2) NULL,
CC_WBS NVARCHAR (4)  NULL,
CA_WBS NVARCHAR (4) NULL,
ProfitCenter NVARCHAR (10) NULL,
ObjectNumber NVARCHAR (22) NULL,
CreatedDate DATE NULL,
CreatedUser NVARCHAR (12) NULL,
UpdatedDate DATE NULL,
UpdatedName NVARCHAR (12) NULL,
PROJMGR_Number NUMERIC(8) NULL,
PROJMGR_Name NVARCHAR (25) NULL,
ApplicantNumber NUMERIC(8) NULL,
Applicant NVARCHAR (25) NULL,
UserDefinedID NVARCHAR(	7) NULL,
UserWBSElemet NVARCHAR (20) NULL,
ObjectClass NVARCHAR(	2) NULL,
ZZPRODUCT NVARCHAR (25) NULL,
ZZSTAGE NVARCHAR (25) NULL,
ZZSFDC NVARCHAR (25) NULL,
ZZDXCMH NVARCHAR (25) NULL,
ZZIWO_NO NVARCHAR (25) NULL,
Regulatory_Ind NVARCHAR(4) NULL,
Combination_Status NUMERIC (3) NULL,
LoadDate DATE NOT NULL
CONSTRAINT [PK_lt_FTP_WBS] PRIMARY KEY CLUSTERED 
(
	[WBS_Element] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

