USE [OptimusPrime]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
DROP TABLE IF EXISTS dbo.lt_Sales_Order_WBS

CREATE TABLE [dbo].[lt_Sales_Order_WBS](
SalesDocument NVARCHAR (10) NOT NULL,
Item NUMERIC (6) NULL,
ProfitSegment NUMERIC (10) NULL,
LoadDate DATE NOT NULL
CONSTRAINT [PK_lt_Sales_Order_WBS] PRIMARY KEY CLUSTERED 
(
	[SalesDocument] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO