INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1502', 'Arab-Emirates Sales','AE', 'Utd.Arab Emir.')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1131', 'Argentina Local Sales','AR', 'Argentina')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1419', 'Austria Sales','AT', 'Austria')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1634', 'Australia Sales','AU', 'Australia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2033', 'Barbados','BB', 'Barbados')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1380', 'Belgium Sales','BE', 'Belgium')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1455', 'Bulgaria Sales','BG', 'Bulgaria')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2034', 'Bermuda','BM', 'Bermuda')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2027', 'Brunei Balance Sheet','BN', 'Brunei')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1088', 'Brazil Sales','BR', 'Brazil')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2032', 'Bahamas','BS', 'Bahamas')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1079', 'Canada Sales','CA', 'Canada')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1423', 'Switzerland Sales','CH', 'Switzerland')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1139', 'Chile Sales','CL', 'Chile')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1679', 'China Sales','CN', 'China')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1108', 'Colombia Sales','CO', 'Colombia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1099', 'Caribbean Local Sales','CY', 'Cyprus')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1428', 'Czech Sales','CZ', 'Czech Republic')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1328', 'Germany Sales','DE', 'Germany')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1383', 'Denmark Sales','DK', 'Denmark')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1964', 'Domincan Rep. Local Sales','DO', 'Dominican Rep.')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1485', 'Algeria Sales','DZ', 'Algeria')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1113', 'Ecuador Sales','EC', 'Ecuador')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1507', 'Egypt Sales','EG', 'Egypt')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1414', 'Spain Sales','ES', 'Spain')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1386', 'Finland Sales','FI', 'Finland')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2110', 'SPAC HQ','FJ', 'Fiji')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1369', 'France Sales','FR', 'France')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1357', 'UK Sales','GB', 'United Kingdom')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1664', 'Hong Kong Sales','HK', 'Hong Kong')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2015', 'Honduras','HN', 'Honduras')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1447', 'Hungary Sales','HU', 'Hungary')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1617', 'Indonesia Sales','ID', 'Indonesia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1346', 'Ireland Sales','IE', 'Ireland')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1434', 'Israel Sales','IL', 'Israel')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1709', 'India Sales','IN', 'India')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1374', 'Italy Sales','IT', 'Italy')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1965', 'Jamaica Local Sales','JM', 'Jamaica')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1511', 'Jordan Sales','JO', 'Jordan')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1559', 'Japan Sales','JP', 'Japan')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1099', 'Caribbean Local Sales','KN', 'St Kitts&Nevis')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1699', 'Korea Local Sales','KR', 'South Korea')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2035', 'Cayman Island','KY', 'Cayman Islands')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1513', 'Lebanon Sales','LB', 'Lebanon')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1389', 'Lithuania Sales','LT', 'Lithuania')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1379', 'Luxemburg Sales','LU', 'Luxembourg')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1494', 'Morocco Sales','MA', 'Morocco')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1949', 'Mauritius Sales','MU', 'Mauritius')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1146', 'Mexico Sales','MX', 'Mexico')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1600', 'Malaysia Sales','MY', 'Malaysia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1396', 'Netherland Sales','NL', 'Netherlands')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1403', 'Norway Sales','NO', 'Norway')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1654', 'New Zealand Sales','NZ', 'New Zealand')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1515', 'Oman Sales','OM', 'Oman')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1967', 'Panama Local Sales','PA', 'Panama')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1124', 'Peru Sales','PE', 'Peru')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1623', 'Philippines Sa','PH', 'Philippines')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1437', 'Poland','PL', 'Poland')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1411', 'Portugal Sales','PT', 'Portugal')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1516', 'Qatar Sales','QA', 'Qatar')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1465', 'Romania Sales','RO', 'Romania')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1469', 'Serbia Sales','RS', 'Serbia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1450', 'Russia Sales','RU', 'Russian Fed.')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1517', 'Saudi Sales.','SA', 'Saudi Arabia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1406', 'Sweden Sales','SE', 'Sweden')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1581', 'Singapore Sales','SG', 'Singapore')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1441', 'Slovakia Sales','SK', 'Slovakia')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1953', 'Swaziland Sales','SZ', 'Swaziland')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1607', 'Thailand Sales','TH', 'Thailand')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1444', 'Turkey Sales','TR', 'Turkey')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2014', 'Trinidad and Tobago','TT', 'Trinidad,Tobago')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1692', 'Taiwan Sales','TW', 'Taiwan')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1482', 'Ukrainia Sales','UA', 'Ukraine')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2007', 'US Sales','US', 'USA')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1137', 'Uruguay Sales','UY', 'Urugray')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2021', 'Cyprus Sales','VG', 'British Virgin Islands')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1099', 'Caribbean Local Sales','VI', 'Amer.Virgin Is.')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P1620', 'Vietnam Sales','VN', 'Vietnam')
INSERT INTO bmt_Table1_Country (HZ_PC_Code, HZ_PC_Desc, CountryCode, CountryName) VALUES ('P2010', 'Southern Africa Sales','ZA', 'South Africa')
